### ISSUE TITLE
saveFileAs can't save file properly when dots are part of the filename

### ISSUE THREAD

**Issue by michaelklopf** [cogniteev/ember-cli-file-saver#10]
Hi,

I just learned that the saveFileAs method has trouble with filenames that include dots.

Example:

`this.saveFileAs("filename.with.dots", request.response, "application/pdf");`

creates a file with the filename `filename.with.dots`.

Replacing the dots like this

`this.saveFileAs("filename.with.dots".replace(/\./g,' '), request.response, "application/pdf");`

produces the output with filename `filename with dots.pdf`.

I see that in the code you use the File api, so a solution could be to sanitize the string?

```
  saveFileAs(filename, content, contentType) {
    this.saveAs(new File([ content], filename.replace(/\./g,' '), { type: contentType }));
  },
```

I think we will filter the dots out in our backend but it's not forbidden to use them in general, so maybe this should be filtered out in this method somehow.

**Comment by panthony** [comment]
@michaelklopf The mixin should not temper with filenames, this is simply a proxy to FileSaver library.

I'm guessing the File API (or FileSaver?) try to infer the extension from the content type if not provided in the filename (case where no '.' exists in the filename).

But passing the extension with the filename (`filename.with.dots.pdf`) should do the trick, no?

**Comment by michaelklopf** [comment]
Yes, you are right, this way it works. Well ok, I think all questions were answered and I'll close the issue.
