### ISSUE TITLE
Send json and receive arraybuffer

### ISSUE THREAD

**Issue by louim** [cogniteev/ember-cli-file-saver#14]
Hi, maybe i'm missing something obvious, but is it possible to send json data but receive an arraybuffer?

```
this.get('ajax')
  .raw('/employees_exports', {
    method: 'POST',
    data : { my_param1: 'value1', my_param2: value2 },
    dataType: 'arraybuffer',
    processData: false
  })
  .then(({ jqXHR, response }) => {
    const contentType = jqXHR.getResponseHeader('content-type');
    const disposition = jqXHR.getResponseHeader('content-disposition');
    const [, filename] = disposition.match(/.*filename="([\w.]*)"/);
    this.saveFileAs(filename, response, contentType);
  });
```
My use-case is passing some filters to the backend, and receive a file based on the data I passed. But sadly, the data gets passed as "[object Object]" to the backend.

**Comment by panthony** [comment]
@louim Hi, did you try passing `data: JSON.stringify({ my_param1: 'value1' })` instead?

**Comment by louim** [comment]
Hey!
Sorry about that. That was my fault, I forgot to set the `contentType: 'application/json',` on the call (EmberAjax does the JSON.stringify if you set the contentType). It worked before the `dataType` change to `arraybuffer`, but only because it was sending the data as FormData, and my Rails backend was decoding the FormData into valid params. So I tought that the `dataType` change was the cause.

Thanks for the quick help.
