### ISSUE TITLE
Get the filename and contentType from a component?

### ISSUE THREAD

**Issue by stephanebruckert** [cogniteev/ember-cli-file-saver#22]
Hello,

```
invoiceModel
  .download()
  .then((pdfContent) => this.saveFileAs('invoice.pdf', pdfContent, 'application/pdf'));
```

From a model/component, can't we get the filename and contentType using `this.get('filename')` and `this.get('contentType')`? It looks undefined whereas it seems possible using `ajax`.

Thank you!

**Comment by panthony** [comment]
@stephanebruckert You always have to provide the filename & the content type yourself.

The exemple in component should have added a filename & contentType property as an exemple:

```javascript
export default Component.extend(FileSaverMixin, {

  tagName: 'button',
 
  // missing from README
  filename: 'invoice.pdf', 
  contentType: 'application/pdf',

  click() {
    this.get('ajax').request(this.get('downloadUrl'), {
      method: 'GET',
      dataType: 'arraybuffer', // or 'blob'
      processData: false
    })
    .then((content) => this.saveFileAs(this.get('filename'), content, this.get('contentType')));
  }
});
```

**Comment by stephanebruckert** [comment]
Ha I see, ok! Thanks

Because the request response headers do contain the contentType + filename, do you think it would be possible to make use of it? In my case I would like to use the exact filename that is coming from the API.

**Comment by panthony** [comment]
@stephanebruckert This is out of the scope of this addon so I can't tell you.

You have to check how to access response headers for the service you are using to retrieve the payload.

**Comment by stephanebruckert** [comment]
That's OK, I'm now duplicating this information in both the frontend and backend!

Closing as solved, as I now know that we can't do it from `ajax` either. 

Many thanks for the swift responses!
