### ISSUE TITLE
Can't save JPG, not sure what I'm missing

### ISSUE THREAD

**Issue by BMahabir** [cogniteev/ember-cli-file-saver#8]
I have raw JPG data that looks like this in my variable called jpg :  

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgM .......... AAf/Z

I execute this statement in my code :  

this.saveFileAs('map.jpg', jpg, 'image/jpeg');

A file called map.jpg downloads.  I try to open it, but it appears to be corrupted and no sort of image software, chrome, anything is able to open it.  I inspect the file in notepad, and it is simply one long line with the string above (which I know is not correct, it should be completely unreadable/encoded/etc).  I also try to substring out the "data:image/jpeg;base64," part, but that doesn't make a difference.

I know that the raw data is valid because I am able to use an Image object and new browser window to open the image and it displays correctly.

Any help would be appreciated!

**Comment by panthony** [comment]
I'm simply doing a proxy to FileSaver library.

Apparently you have to convert your data URI as an array of bytes (that will passed to FileSaver using a `Blob`).

https://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata?answertab=votes#tab-top

**Comment by panthony** [comment]
Issue not related to this plugin, closing.
