### ISSUE TITLE
saveAs(new File(...) Does Not work in IE11, IE Edge

### ISSUE THREAD

**Issue by ShenglinGuo** [cogniteev/ember-cli-file-saver#9]
The saveAs method from mixin currently does not work with any of the of IE browsers. You will get "saveAs() is not a function" or "object does not accept this action" 

I have searched for a few hours and eventually come across this post 
https://stackoverflow.com/questions/39266801/saving-file-on-ie11-with-filesaver?rq=1

saveAs(new File([content], filename, {type : mimeType}) does not work for any of the IE browser including edge.

The method signature works for IE is 
saveAs(new Blob([content], {type : mimeType}), fileName);

So I end up import filesaver instead of using the mixin

suggest to change the mixin method line 16 to use the blob compare the file object for better compatibility with IE family of browsers.

Hope this information can help other people later when they come across this problem.

**Comment by michaelklopf** [comment]
Hit the same issue.

**Comment by panthony** [comment]
@ShenglinGuo @michaelklopf I published the version `1.1.1` using the `Blob` API directly instead of `File` API as suggested.

Hopefully it will fixes your issue.

Thanks for reporting 👍

**Comment by michaelklopf** [comment]
@panthony 

We tested it and file download works, but files are not downloaded with a file extension.

The filename must include the extension. Either FileSaver.js is filling that bridge for us, but not for IE, or the Blob API on IE is different.

**Comment by panthony** [comment]
@michaelklopf I don't know I always passed the extension as part of the filename and I never had an issue with this.

This is probably a browser specific behavior since I doubt FileSaver is keeping a map between all possible mime types and their corresponding extension.

**Comment by ShenglinGuo** [comment]
@panthony Thanks for fixing this.

for this saveAs(new Blob([content], {type : mimeType}), fileName); to work, you will need to get the mimeType and fileName from xhr headers. The mimeType need to be specified properly in order for it to work. I am not using Ember Data. 

e.g.
```javascript
const mimeType = xhr.getResponseHeader('Content-Type');

getFileNameFromXhr : function(xhr){
        let filename = "file";
        const disposition = xhr.getResponseHeader('Content-Disposition');
        if (disposition) {
            const filenameRegex = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/;
            const matches = filenameRegex.exec(disposition);
            if (matches != null && matches[1]) {
                filename = matches[1].replace(/['"]/g, '');
            }
        }
        return filename;
    },
```
Just as additional information for people struggling with preview file e.g. open new tab and show pdf, you need to use a separate function for IE

```javascript
const responseBlob = new Blob([response], { type: self.getMimeTypeFromXhr(xhr) });
                if(window.navigator.msSaveOrOpenBlob) { // for IE
                    window.navigator.msSaveOrOpenBlob(responseBlob, self.getFileNameFromXhr(xhr));
                }else{ // for other browsers
                    const url = URL.createObjectURL(responseBlob, self.getFileNameFromXhr(xhr));
                    window.open(url);
                }
```
